# -*- coding: utf-8 -*-
# -*- author: Jiangtao -*-


"""
第一位为 1
中间两位 代表业务类型
0 通信成功
10 通信失败
200 请求成功并返回数据
00 服务端错误
01 短信业务错误
02 用户相关业务错误
03 空间相关业务错误
04 计划相关业务错误
05 素材相关业务错误
06 验证相关业务
07 数据相关业务
08 产品相关业务

最后三位 代表具体业务报错

"""
APP_SUCCESS = 200
SUCCESS = 0
ERROR = 10

SERVER_ERROR = 100000
PARAM_ERROR = 100001
PARAM_MISS = 100002

SMS_SEND_ERROR = 101000
SMS_TYPE_NOT_FOUND = 101001
SMS_TIMES_TOO_MANY = 101002
SMS_CHECK_ERROR = 101003

USER_NOT_FOUND = 102000
USER_IS_EXIST = 102001
USER_IS_DISABLED = 102002
USER_PWD_ERROR = 102003
USER_REGISTER_USERNAME_OR_PASSWORD_MISS = 102004
USER_NICKNAME_ALREADY = 102005
USER_NICKNAME_TOO_LONG = 102006
USER_LOGIN_FREQUENTLY = 102007
USER_PWD_CONFIRM_NOT_MATCH = 102008
USER_ACCOUNT_TOO_SHORT = 102009
USER_ACCOUNT_CHAR_NOT_ALLOWED = 102010
USER_NICKNAME_CHAR_NOT_ALLOWED = 102011
USER_PWD_TOO_SHORT = 102012
USER_PWD_DISABLED = 102013
USER_EMAIL_DISABLED = 102014
USER_QQ_DISABLED = 102015
USER_MOBILE_DISABLED = 102016
USER_IS_NOT_ALLOWED = 102017
USER_IS_NOT_LOGIN = 102018
USER_LOGIN_ERROR = 102019

ZONE_NOT_FOUND = 103000
ZONE_IS_EXIST = 103001
ZONE_IS_DISABLED = 103002

PLAN_NOT_FOUND = 104000
PLAN_IS_EXIST = 104001
PLAN_IS_DISABLED = 104002

MATERIAL_NOT_FOUND = 105000
MATERIAL_IS_EXIST = 105001
MATERIAL_IS_DISABLED = 105002

VERIFY_ERROR = 106000

DATA_NOT_FOUND = 107000

APP_NOT_FOUND = 108000

MSG = {
    APP_SUCCESS: 'success',
    SUCCESS: 'success',
    ERROR: 'error',
    SERVER_ERROR: '服务器错误',
    PARAM_ERROR: '参数错误',
    PARAM_MISS: '缺少参数',

    SMS_SEND_ERROR: '短信发送失败',
    SMS_TYPE_NOT_FOUND: '短信类型错误',
    SMS_TIMES_TOO_MANY: '短信发送到达最大上限',
    SMS_CHECK_ERROR: '短信验证失败',

    USER_NOT_FOUND: '用户不存在',
    USER_IS_EXIST: '用户已存在',
    USER_IS_DISABLED: '用户被禁用',
    USER_PWD_ERROR: '用户密码错误',
    USER_REGISTER_USERNAME_OR_PASSWORD_MISS: '用户名或密码缺失',
    USER_NICKNAME_ALREADY: '用户昵称已存在',
    USER_NICKNAME_TOO_LONG: '用户昵称长度过长',
    USER_LOGIN_FREQUENTLY: '登录次数过多请稍后重试',
    USER_PWD_CONFIRM_NOT_MATCH: '用户确认密码与密码不符',
    USER_ACCOUNT_TOO_SHORT: '用户名长度过短',
    USER_ACCOUNT_CHAR_NOT_ALLOWED: '用户名非法字符',
    USER_NICKNAME_CHAR_NOT_ALLOWED: '昵称非法字符',
    USER_PWD_TOO_SHORT: '密码长度过短',
    USER_PWD_DISABLED: '密码格式错误',
    USER_EMAIL_DISABLED: '邮箱格式错误',
    USER_QQ_DISABLED: 'QQ格式错误',
    USER_MOBILE_DISABLED: '手机号格式错误',
    USER_IS_NOT_ALLOWED: '用户无权限',
    USER_LOGIN_ERROR: '用户名或密码错误',

    ZONE_NOT_FOUND: '空间不存在',
    ZONE_IS_EXIST: '空间已存在',
    ZONE_IS_DISABLED: '空间被禁用',

    PLAN_NOT_FOUND: '计划不存在',
    PLAN_IS_EXIST: '计划已存在',
    PLAN_IS_DISABLED: '计划被禁用',

    MATERIAL_NOT_FOUND: '素材不存在',
    MATERIAL_IS_EXIST: '素材已存在',
    MATERIAL_IS_DISABLED: '素材被禁用',

    VERIFY_ERROR: '验证码错误，请重新输入',

    DATA_NOT_FOUND: '没有数据',

    APP_NOT_FOUND: '产品不存在',
}
